### PR TITLE
CI Testing Pipeline

### LINKED ISSUE #25: Test cases
1. Expand the MiniZinc `maccGradedSmallGen` test case (currently with chuffed) with the following solvers:
- or-tools, yuck, picat, gecode

2. Expand the (not yet existing) Essence test case with the following solvers:
- chuffed, minion, or-tools, kissat

### PR DESCRIPTION
**Pull request by vincepick**
This Pull Request includes the addition of the CI pipeline and the testing scripts.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
so just like we discussed this was a trivial change (!) I see :)

often gremlins hide in CI work. @niklasdewally had a good meme about fighting with CI in the oxide repo.

**Comment by ndangtt** [comment]
TODO:

1. `scripts/testScript`:
- add a short description at the beginning of `check.sh` and `check-pr.sh` to summarise what they are doing.

2. Add a similar small case for Essence graded: use VesselLoading (may need to wait until the graded PR is complete and merged into the `dev` branch)

**Comment by ndangtt** [comment]
@vincepick: thank you very much for creating the tests and the PR! To aid the review process and help future developers of this repo, could you please help add a summary of the tests created and the scripts? Many thanks!

**Comment by vincepick** [comment]
> @vincepick: thank you very much for creating the tests and the PR! To aid the review process and help future developers of this repo, could you please help add a summary of the tests created and the scripts? Many thanks!

Hi @ndangtt ,

Yes of course, I would be happy to.  There is the existing summary in the [testreadme.md](https://github.com/vincepick/AutoIG/blob/test/maccGradedCase/scripts/testScripts/testreadme.md) file, and I would be happy to elaborate, but am not entirely sure what parts I should be focusing on. Could you let me know which specific areas you'd like me to touch on further?  I will add them to the testreadme as well right away. 

Thank you,
Vincent

**Pull request merged**
